import "./globals.css";
import { Raleway } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

export const raleway = Raleway({ subsets: ["latin"] });
 export const  space_grotesk =  Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>{children}</body>
    </html>
  );
}
